language: rust
os:
    - linux
    - osx
env:
    global:
        - LD_LIBRARY_PATH: /usr/local/lib
install:
    - sudo apt-get install libXxf86vm-dev
    - git clone https://github.com/glfw/glfw.git
    - cd glfw
    - git checkout 3.0.3
    - cmake -DCMAKE_C_FLAGS=-fPIC -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF .
    - make
    - sudo make install
    - cd ../
before_script:
    - rustc -v
    - cargo -V
script:
    - cd ./getting-started
    - cargo build -v
    - cargo test -v
