[package]

name = "getting-started"
version = "0.0.0"
authors = ["TyOverby <ty@pre-alpha.com>"]

[dependencies.piston]

git = "https://github.com/PistonDevelopers/piston"

[dependencies.glfw_game_window]

git = "https://github.com/PistonDevelopers/glfw_game_window.git"

[dependencies.graphics]

git = "https://github.com/PistonDevelopers/rust-graphics.git"

[dependencies.opengl_graphics]

git = "https://github.com/PistonDevelopers/opengl_graphics.git"

[[bin]]

name = "game"
path = "./src/game.rs"
